extension: ['.spec.js']
#parallel: true
reporter: 'mochawesome'
reporter-option:
 - 'reportDir=report'
 - 'reportFilename=index'
 - 'quiet=true'
require:
 - './src/jsdom.js'
 - '@babel/register'
slow: 100
spec: 'src/**/*.spec.js'
timeout: 1000
watch: true
watch-files: 'src/**/*.js'