extension: ['.spec.js']
#recursive: true
#parallel: true                       # doesn't work with intellij-mocha
require: '@babel/register'
##reporter: 'mochawesome'
##reporter-option:
## - 'reportDir=report'
## - 'reportFilename=index'
## - 'quiet=true'
#slow: 100
spec:
 - 'src/**/*.spec.js'
#timeout: 5000
#ui: 'bdd'
#watch: true
##watch-files:
## - './src/**/*.js'
##watch-ignore:
## - './mochawesome-report/'